{"name": "Проверка получения ошибки \"Учетная запись не найдена\" при передачи в теле запроса неправильных данных полей логина или пароля", "status": "passed", "parameters": [{"name": "incorrectly_filled_in_fields", "value": "{'login': 'lindath', 'password': 'invalid_password'}"}], "start": 1744368074974, "stop": 1744368075196, "uuid": "3b2a4c9f-94aa-485c-a883-94132e9b2abb", "historyId": "496a27db88edd581b6681ff0d4673292", "testCaseId": "a6fe86b6256607a65c10d1f15a41e383", "fullName": "tests.test_check_login_courier.TestCheckLoginCourier#test_login_courier_with_incorrect_loginor_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_check_login_courier"}, {"name": "subSuite", "value": "TestCheckLoginCourier"}, {"name": "host", "value": "Martin"}, {"name": "thread", "value": "29744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_check_login_courier"}]}